hlky/stable-diffusion:
  - source: webui.py
    dest: scripts/webui.py
  - source: relauncher.py
    dest: scripts/relauncher.py
  - source: txt2img.yaml
    dest: txt2img.yaml
  - source: webui.yaml
    dest: configs/webui/webui.yaml
  - source: readme.md
    dest: readme.md
  - source: .gitignore/.idea/.gitignore
    dest: .gitignore/.idea/.gitignore
  - source: frontend/__init__.py
    dest: frontend/__init__.py
  - source: frontend/css_and_js.py
    dest: frontend/css_and_js.py
  - source: frontend/frontend.py
    dest: frontend/frontend.py
  - source: frontend/ui_functions.py
    dest: frontend/ui_functions.py