img2img:
  base_size: 512
  batch_count: 1
  batch_size: 1
  cfg_scale: 7.5
  codeformer_weight: 0.5
  color_correct: true
  denoising_strength: 0.35
  do_exact_steps: true
  face_restorer: CodeFormer
  filter_nsfw: false
  firstphase_height: 512
  firstphase_width: 512
  highres_fix: false
  include_grid: false
  inpaint_full_res: false
  inpaint_full_res_padding: 0
  inpaint_mask_weight: 1.0
  inpainting_fill: 1
  invert_mask: false
  mask_blur: 0
  max_size: 768
  mode: 0
  negative_prompt: ''
  prompt: dog
  resize_mode: 1
  restore_faces: false
  sample_path: outputs/krita-out
  sampler_name: Euler a
  save_samples: false
  script: None
  script_args: []
  sd_model: model.ckpt
  seed: -1
  seed_enable_extras: false
  seed_resize_from_h: 0
  seed_resize_from_w: 0
  steps: 50
  subseed: -1
  subseed_strength: 0.0
  tiling: false
  upscaler_name: None
plugin:
  sample_path: outputs/krita-in
  save_samples: false
txt2img:
  base_size: 512
  batch_count: 1
  batch_size: 1
  cfg_scale: 7.5
  codeformer_weight: 0.5
  denoising_strength: 0.35
  face_restorer: CodeFormer
  filter_nsfw: false
  firstphase_height: 512
  firstphase_width: 512
  highres_fix: false
  include_grid: false
  max_size: 768
  negative_prompt: ''
  prompt: dog
  restore_faces: false
  sample_path: outputs/krita-out
  sampler_name: Euler a
  save_samples: false
  script: None
  script_args: []
  sd_model: model.ckpt
  seed: -1
  seed_enable_extras: false
  seed_resize_from_h: 0
  seed_resize_from_w: 0
  steps: 30
  subseed: -1
  subseed_strength: 0.0
  tiling: false
  upscaler_name: None
upscale:
  downscale_first: false
  sample_path: outputs/krita-out
  save_samples: false
  upscaler_name: None
