version: "3.10.6"
services:
  app:
    environment:
      - PORT=5001
      - ENV=prod
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "5001:5001"
