name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: Tell us what happened in a very clear and simple way
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step information to reproduce the bug
      value: 1. Go to .... |
        2. Press ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: What should have happened?
      description: tell what you think the normal behavior should be
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Commit where the problem happens
      description: Which commit are you running ? (copy the **Commit hash** shown in the cmd/terminal when you launch the UI)
  - type: dropdown
    id: os
    attributes:
      label: What OS do you use to run the webui?
      multiple: true
      options:
        - Colab/Runpod or Cloud based
        - Windows
        - Linux
        - MacOS
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers do you use to run the UI ?
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Brave
        - Apple Safari
        - Microsoft Edge
  - type: textarea
    id: cmdargs
    attributes:
      label: Command Line Arguments
      description: Are you using any launching parameters/command line arguments (modified webui-user.py) ? If yes, please write them below
      render: Shell
  - type: textarea
    id: misc
    attributes:
      label: Additionnal information, context and logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
