name: Bug Report
description: You think somethings is broken in the UI
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits.
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, don't forget to fill "What OS..." and "What browsers" and *provide screenshots if possible**
  - id: what-did
    type: textarea
    attributes:
      label: What happened?
      description: Tell us what happened in a very clear and simple way.
    validations:
      required: true
  - id: steps
    type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step information on how to reproduce the bug.
      value: |
        1. Go to ....
        2. Press ....
        3. ...
    validations:
      required: true
  - id: what-should
    type: textarea
    attributes:
      label: What should have happened?
      description: What you think the normal behavior should be.
    validations:
      required: true
  - id: commit
    type: input
    attributes:
      label: Commit where the problem happens
      description: Which commit are you running? (Do not write *Latest version/repo/commit*, as this means nothing and will have changed by the time we read your issue. Rather, copy the **Commit hash** shown in the cmd/terminal when you launch the UI)
    validations:
      required: true
  - id: platforms
    type: dropdown
    attributes:
      label: What platforms do you use to access the UI?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - iOS
        - Android
        - Other/Cloud
    validations:
      required: true
  - id: browsers
    type: dropdown
    attributes:
      label: What browsers do you use to access the UI?
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Brave
        - Apple Safari
        - Microsoft Edge
    validations:
      required: true
  - id: cmdargs
    type: textarea
    attributes:
      label: Command Line Arguments
      description: If you are using any launch parameters/command line arguments (modified webui-user.py) please write them below
      render: Shell
  - id: misc
    type: textarea
    attributes:
      label: Additional information, context and logs
      description: Please provide us with any relevant additional info, context or log output.
