blank_issues_enabled: false
contact_links:
  - name: WebUI Community Support
    url: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions
    about: Please ask and answer questions here.
