services:
  stable-diffusion-webui:
    runtime: nvidia
    image: ghcr.io/emsi/stable-diffusion-webui
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../embeddings:/stable-diffusion-webui/embeddings
      - ../extensions:/stable-diffusion-webui/extensions
      - ../interrogate:/stable-diffusion-webui/interrogate
      - ../models:/stable-diffusion-webui/models
      - ../outputs:/stable-diffusion-webui/outputs
      - ../repositories:/stable-diffusion-webui/repositories
      - home:/root
    command: python3 launch.py --listen

volumes:
  home:
