[paths]
source = inputs/facefusion/source/example-source.jpg
target = inputs/facefusion/target/example-target.jpg
output = outputs/facefusion/example-output.jpg

[options]
# Windows NVIDIA: cuda
# Windows fallback: directml or cpu
# macOS: coreml or cpu
execution_providers = cuda
